
export const allModels = [
    // --- FREE OPERATIVES (Verified live on OpenRouter) ---
    {
        id: "llama-3.3-70b",
        name: "Meta: Llama 3.3 70B Instruct",
        description: "Meta's powerful 70B Llama 3.3 model, optimized for instruction following and dialogue.",
        context: "128K tokens",
        openRouterId: "meta-llama/llama-3.3-70b-instruct:free",
        isFree: true,
        useCases: ["Dialogue", "Creative Writing", "Summarization", "Coding"],
    },
    {
        id: "llama-3.2-3b",
        name: "Meta: Llama 3.2 3B Instruct",
        description: "Meta's compact 3B Llama 3.2 model, great for fast, lightweight tasks.",
        context: "128K tokens",
        openRouterId: "meta-llama/llama-3.2-3b-instruct:free",
        isFree: true,
        useCases: ["Dialogue", "Summarization"],
    },
    {
        id: "gemma-3-27b",
        name: "Google: Gemma 3 27B",
        description: "Google's most capable open-source Gemma 3 model with strong reasoning.",
        context: "128K tokens",
        openRouterId: "google/gemma-3-27b-it:free",
        isFree: true,
        useCases: ["Dialogue", "Coding", "Summarization", "Creative Writing"],
    },
    {
        id: "gemma-3-12b",
        name: "Google: Gemma 3 12B",
        description: "Google's mid-size Gemma 3 model, balancing speed and intelligence.",
        context: "128K tokens",
        openRouterId: "google/gemma-3-12b-it:free",
        isFree: true,
        useCases: ["Dialogue", "Coding", "Summarization"],
    },
    {
        id: "hermes-3-405b",
        name: "NousResearch: Hermes 3 405B",
        description: "A powerful 405B model fine-tuned for instruction following and reasoning.",
        context: "128K tokens",
        openRouterId: "nousresearch/hermes-3-llama-3.1-405b:free",
        isFree: true,
        useCases: ["Dialogue", "Creative Writing", "Coding", "Summarization"],
    },
    {
        id: "nemotron-super-120b",
        name: "NVIDIA: Nemotron Super 120B",
        description: "NVIDIA's high-performance 120B model, optimized for complex reasoning and agentic tasks.",
        context: "128K tokens",
        openRouterId: "nvidia/nemotron-3-super-120b-a12b:free",
        isFree: true,
        useCases: ["Dialogue", "Coding", "Summarization"],
    },
    {
        id: "gpt-oss-120b",
        name: "OpenAI: GPT OSS 120B",
        description: "OpenAI's open-source 120B model available via OpenRouter for free.",
        context: "128K tokens",
        openRouterId: "openai/gpt-oss-120b:free",
        isFree: true,
        useCases: ["Dialogue", "Creative Writing", "Coding", "Summarization"],
    },
    {
        id: "qwen3-80b",
        name: "Qwen: Qwen3 80B Instruct",
        description: "Qwen's latest 80B model with strong multilingual and coding capabilities.",
        context: "128K tokens",
        openRouterId: "qwen/qwen3-next-80b-a3b-instruct:free",
        isFree: true,
        useCases: ["Dialogue", "Coding", "Summarization", "Creative Writing"],
    },
    // --- PREMIUM OPERATIVES ---
    {
        id: "gemini-1.5-flash",
        name: "Google: Gemini 1.5 Flash",
        description: "Google's fastest production-grade multimodal model.",
        context: "1M tokens",
        openRouterId: "google/gemini-flash-1.5",
        genkitId: 'googleai/gemini-1.5-flash-latest',
        isFree: false,
        useCases: ["Dialogue", "Creative Writing", "Summarization", "Image Analysis"],
    },
    {
        id: "gemini-1.5-pro",
        name: "Google: Gemini 1.5 Pro",
        description: "Google's high-intelligence flagship model with a 2M token context window.",
        context: "2M tokens",
        openRouterId: "google/gemini-pro-1.5",
        genkitId: 'googleai/gemini-1.5-pro-latest',
        isFree: false,
        useCases: ["Dialogue", "Creative Writing", "Summarization", "Image Analysis", "Coding"],
    },
    {
        id: "openai-gpt-4o",
        name: "OpenAI: GPT-4o",
        description: "OpenAI's newest, most advanced flagship model.",
        context: "128K tokens",
        openRouterId: "openai/gpt-4o",
        isFree: false,
        useCases: ["Dialogue", "Creative Writing", "Summarization", "Image Analysis", "Coding"],
    },
    {
        id: "anthropic-claude-3-opus",
        name: "Anthropic: Claude 3 Opus",
        description: "Anthropic's most powerful model for highly complex tasks.",
        context: "200K tokens",
        openRouterId: "anthropic/claude-3-opus",
        isFree: false,
        useCases: ["Dialogue", "Creative Writing", "Summarization", "Coding"],
    },
];
